system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::domain('mag.culturepedia.io')->group(function (){





    Route::any('/post/{magazinePost}',function (\App\MagazinePost $magazinePost){
        return view('magazine')->with(["post"=>$magazinePost,"media"=>asset("storage/magazine/media/".$magazinePost->media[0]->file_name)]);

    });

    Route::any('{query}',function (){
        return view('magazine');
    })->where('query', '.*');;


});




Route::get('/',"GuestController@index");
Route::get('/articles','GuestController@articles');
Route::get('/search','GuestController@search');
Route::get('/article/featured','GuestController@featuredArticle');
Route::get('/article/random','GuestController@randomArticle');
Route::get('/user', 'UserController@index')->name('home');
Route::get('/terms_of_use','GuestController@termsOfUse');
Route::get('/privacy_policy','GuestController@privacyPolicy');
Route::get('/contact-us','GuestController@contact');
Route::post('/contact','GuestController@sendMessage');

Route::group(['prefix'=>'user'],function (){
    Route::get('/', 'UserController@index')->name('home');
    Route::get('/article/create', 'UserController@createArticle');
    Route::get('/articles/unapproved', 'UserController@unapprovedArticles');
    Route::get('/articles/approved', 'UserController@approvedArticles');
    Route::get('/articles', 'UserController@articles');
    Route::post('/article','ArticleController@store');
    Route::delete('/article/{id}','ArticleController@destroy');
    Route::get('/article/{article}/edit','UserController@editArticle');
    Route::put('/article/{id}','ArticleController@update');
    Route::put('account/update','UserController@updateAccount')->name('user.update');
    Route::put('account/password','UserController@updatePassword')->name('user.password');
});



Route::middleware(['auth'])->group(function (){
    Route::get('/article/create','ArticleController@create');
    Route::post('/article','ArticleController@store');
    Route::get('/my_articles','ArticleController@index');
    Route::delete('/article/{id}','ArticleController@destroy');
    Route::get('article/{article}/edit','ArticleController@edit');
    Route::put('article/{id}','ArticleController@update');
});


Route::group(['prefix'=>'admin','namespace'=>'Admin'],function (){
    Route::get('/','Auth\LoginController@showLoginForm');
    Route::get('/login','Auth\LoginController@showLoginForm');
    Route::post('login', 'Auth\LoginController@login')->name('admin.login');
    Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    Route::post('register', 'Auth\RegisterController@register')->name('admin.register');
});

Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>'auth:admin'],function (){
    Route::get('dashboard','AdminController@dashboard');
    Route::get('article/create','AdminController@createArticle');
    Route::get('articles/all','AdminController@allArticles');
    Route::get('articles/unapproved','AdminController@unapprovedArticles');
    Route::get('articles/approved','AdminController@approvedArticles');
    Route::get('articles','AdminController@articles');
    Route::get('users/all','AdminController@users');
    Route::get('article/unapproved','AdminController@unapprovedArticles');
    Route::post('article/store','ArticleController@store')->name('admin.article.store');
    Route::delete('article/{id}','ArticleController@destroy');
    Route::get('article/{article}/edit','AdminController@editArticle');
    Route::put('article/{id}','ArticleController@update');
    Route::put('article/approve/{id}','ArticleController@approve');
    Route::put('article/disapprove/{id}','ArticleController@disapprove');
    Route::put('account/update','AdminController@updateAccount')->name('admin.update');
    Route::put('account/password','AdminController@updatePassword')->name('admin.password');
    Route::get('messages','AdminController@messages');
    Route::get('message/{message}','AdminController@getMessage');
    Route::delete('message/{id}','AdminController@deleteMessage');
});

Route::get('article/{article}/{slug}',"GuestController@article");

system/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $primaryKey = "article_id";

    public function videos(){
        return $this->hasMany('App\Video','article_id');
    }

    public function pictures(){
        return $this->hasMany('App\Picture','article_id');
    }


    public function getUpdatedAtAttribute($timestamp) {
        $date = new \DateTime($timestamp);
            $date = $date->format('F d, Y');
        return $date;
    }

    public function  getCreatedAtAttribute($timestamp){
        $date = new \DateTime($timestamp);
        $date = $date->format('F d, Y');
        return $date;
    }
}

system/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable,HasApiTokens;
    protected $primaryKey = "user_id";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function  getCreatedAtAttribute($timestamp){
        $date = new \DateTime($timestamp);
        $date = $date->format('F d, Y');
        return $date;
    }
}

system/resources/views/admin/admin_articles.blade.php
@extends('admin.master')
@section('styles')
    @parent
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/datatables/datatables.css') }}">
@endsection
@section('title','My Articles')
@section('page-title','My Articles')

@section('header-title')
    <h1><span class="fa fa-list"></span> My Article <small>Manage your articles</small></h1>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page"> My Articles</li>
@endsection
@section('content')
 <div class="card">
     <div class="card-header">
         My Articles
     </div>
     <div class="card-body">
         <div class="admin-articles">
             <div class="articles">
                 @if(session('delete_success'))
                     <div class="alert alert-success">
                         <p>{{ session('delete_success') }}</p>
                     </div>
                 @endif
                 <table class="table">
                     <thead>
                     <tr>
                         <th width="1%">S/N</th>
                         <th>Title</th>
                         <th width="1%">View</th>
                         <th width="1%">Edit</th>
                         <th width="1%">Delete</th>
                     </tr>
                     </thead>
                     <tbody>
                     @foreach($articles as $article)
                         <tr>
                             <td>{{ $loop->index+1 }}</td>
                             <td>{{ $article->title }}</td>
                             <td><a  href="{{ url('article/'.$article->article_id.'/'.str_slug($article->title)) }}" class="btn btn-outline-info btn-sm">View</a></td>
                             <td><a href="{{ url('admin/article/'.$article->article_id.'/edit') }}" class="btn btn-outline-info btn-sm">Edit</a></td>
                             <td>
                                 <form method="post" action=" {{ url('admin/article',['id'=>$article->article_id]) }}">
                                     {{ method_field('DELETE') }}
                                     {{ csrf_field() }}
                                     <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                 </form>
                             </td>
                         </tr>
                     @endforeach
                     </tbody>
                 </table>
             </div>
         </div>
     </div>
 </div>
@endsection
@section('scripts')
    @parent
    <script type="text/javascript" src="{{  asset('assets/datatables/datatables.js') }}"></script>
    <script>
        $(document).ready( function () {
            $('.table').DataTable({
                autoFill: true
            });
        } );
    </script>
@endsection

system/resources/views/admin/all_articles.blade.php
@extends('admin.master')
@section('title','All Articles')
@section('page-title','All Articles')
@section('styles')
    @parent
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/datatables/datatables.css') }}">
@endsection

@section('header-title')
    <h1><span class="fa  fa-align-justify"></span> All Articles <small>Manage all articles</small></h1>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page">All Articles</li>
@endsection



@section('content')
    <div class="card">
        <div class="card-header">
            All Articles
        </div>
        <div class="card-body">
            <div class="admin-articles">
                <div class="articles">
                    @if(session('delete_success'))
                        <div class="alert alert-success">
                            <p>{{ session('delete_success') }}</p>
                        </div>
                    @endif
                    @if(session('approval_success'))
                        <div class="alert alert-success">
                            <p>{{ session('approval_success') }}</p>
                        </div>
                    @endif
                    @if(session('approval_error'))
                        <div class="alert alert-danger">
                            <p>{{ session('approval_error') }}</p>
                        </div>
                    @endif
                    @if(session('disapproval_success'))
                        <div class="alert alert-success">
                            <p>{{ session('disapproval_success') }}</p>
                        </div>
                    @endif
                    @if(session('disapproval_error'))
                        <div class="alert alert-danger">
                            <p>{{ session('disapproval_error') }}</p>
                        </div>
                    @endif
                    <table class="table">
                        <thead>
                        <tr>
                            <th width="1%">S/N</th>
                            <th>Title</th>
                            <th width="5%">Status</th>
                            <th width="1%">View</th>
                            <th width="1%">Approval</th>
                            <th width="1%">Edit</th>
                            <th width="1%">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($articles as $article)
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td>{{ $article->title }}</td>
                                <td>@if($article->approved==true){{ 'Approved' }} @else{{ 'Unapproved' }} @endif</td>
                                <td><a  href="{{ url('article/'.$article->article_id.'/'.str_slug($article->title)) }}" class="btn btn-outline-info btn-sm">View</a></td>

                                <td>
                                    @if($article->approved ==true)
                                        <form method="post" action=" {{ url('admin/article/disapprove',['id'=>$article->article_id]) }}">
                                            {{ method_field('PUT') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-outline-info btn-sm" title="Disapprove article">Disapprove</button>
                                        </form>
                                    @else
                                        <form method="post" action=" {{ url('admin/article/approve',['id'=>$article->article_id]) }}">
                                            {{ method_field('PUT') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-outline-info btn-sm">Approve</button>
                                        </form>
                                    @endif
                                </td>
                                <td><a href="{{ url('admin/article/'.$article->article_id.'/edit') }}" class="btn btn-outline-info btn-sm">Edit</a></td>
                                <td>
                                    <form method="post" action=" {{ url('admin/article',['id'=>$article->article_id]) }}">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    @parent
    <script type="text/javascript" src="{{  asset('assets/datatables/datatables.js') }}"></script>
    <script>
        $(document).ready( function () {
            $('.table').DataTable({
                autoFill: true
            });
        } );
    </script>
@endsection

system/resources/views/admin/approved_article.blade.php
@extends('admin.master')
@section('styles')
    @parent
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/datatables/datatables.css') }}">
@endsection
@section('title','Approved Articles')
@section('page-title','Approved Articles')

@section('header-title')
    <h1><span class="fa  fa-toggle-on"></span> Approved Article <small>Manage approved articles</small></h1>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page">Approved Articles</li>
@endsection
@section('content')

    <div class="card">
        <div class="card-header">
            Approved Articles
        </div>
        <div class="card-body">
            <div class="admin-articles">
                <div class="articles">
                    @if(session('delete_success'))
                        <div class="alert alert-success">
                            <p>{{ session('delete_success') }}</p>
                        </div>
                    @endif
                    @if(session('approval_success'))
                        <div class="alert alert-success">
                            <p>{{ session('approval_success') }}</p>
                        </div>
                    @endif
                    @if(session('approval_error'))
                        <div class="alert alert-danger">
                            <p>{{ session('approval_error') }}</p>
                        </div>
                    @endif
                    @if(session('disapproval_success'))
                        <div class="alert alert-success">
                            <p>{{ session('disapproval_success') }}</p>
                        </div>
                    @endif
                    @if(session('disapproval_error'))
                        <div class="alert alert-danger">
                            <p>{{ session('disapproval_error') }}</p>
                        </div>
                    @endif
                    <table class="table ">
                        <thead>
                        <tr>
                            <th width="1%">S/N</th>
                            <th>Title</th>
                            <th width="5%">Status</th>
                            <th width="1%">View</th>
                            <th width="1%">Approval</th>
                            <th width="1%">Edit</th>
                            <th width="1%">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($articles as $article)
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td>{{ $article->title }}</td>
                                <td>@if($article->approved==true){{ 'Approved' }} @else{{ 'Unapproved' }} @endif</td>
                                <td><a  href="{{ url('article/'.$article->article_id.'/'.str_slug($article->title)) }}" class="btn btn-outline-info btn-sm">View</a></td>

                                <td>
                                    @if($article->approved ==true)
                                        <form method="post" action=" {{ url('admin/article/disapprove',['id'=>$article->article_id]) }}">
                                            {{ method_field('PUT') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-outline-info btn-sm" title="Disapprove article">Disapprove</button>
                                        </form>
                                    @else
                                        <form method="post" action=" {{ url('admin/article/approve',['id'=>$article->article_id]) }}">
                                            {{ method_field('PUT') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-outline-info btn-sm">Approve</button>
                                        </form>
                                    @endif
                                </td>
                                <td><a href="{{ url('admin/article/'.$article->article_id.'/edit') }}" class="btn btn-outline-info btn-sm">Edit</a></td>
                                <td>
                                    <form method="post" action=" {{ url('admin/article',['id'=>$article->article_id]) }}">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('scripts')
    @parent
    <script type="text/javascript" src="{{  asset('assets/datatables/datatables.js') }}"></script>
    <script>
        $(document).ready( function () {
            $('.table').DataTable({
                autoFill: true
            });
        } );
    </script>
@endsection

system/resources/views/admin/dashboard.blade.php
@extends('admin.master')
@section('title','Dashboard')
@section('header-title')
    <h1><span class="fa fa-dashboard"></span> Dashboard<small> Manage your site</small></h1>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active" aria-current="page"> Dashboard</li>
@endsection
@section('content')
    <div class="card overview">
        <div class="card-header">
            Overview
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-4">
                    <div class="item">
                        <h2><span class="fa fa-pencil"></span> {{ number_format($totalArticles) }}</h2>
                        <h4>Total Articles</h4>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="item">
                        <h2><span class="fa fa-pencil"></span> {{ number_format($published) }}</h2>
                        <h4>Published Articles</h4>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="item">
                        <h2><span class="fa fa-users"></span> {{ number_format($totalUsers) }}</h2>
                        <h4>Total Users</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">
            Latest Articles
        </div>
        <div class="card-body">
            <div class="admin-articles">
                <div class="articles">
                    @if(session('delete_success'))
                        <div class="alert alert-success">
                            <p>{{ session('delete_success') }}</p>
                        </div>
                    @endif
                    @if(session('approval_success'))
                        <div class="alert alert-success">
                            <p>{{ session('approval_success') }}</p>
                        </div>
                    @endif
                    @if(session('approval_error'))
                        <div class="alert alert-danger">
                            <p>{{ session('approval_error') }}</p>
                        </div>
                    @endif
                    @if(session('disapproval_success'))
                        <div class="alert alert-success">
                            <p>{{ session('disapproval_success') }}</p>
                        </div>
                    @endif
                    @if(session('disapproval_error'))
                        <div class="alert alert-danger">
                            <p>{{ session('disapproval_error') }}</p>
                        </div>
                    @endif
                    <table class="table table-sm">
                        <thead>
                        <tr>
                            <th width="1%">S/N</th>
                            <th>Title</th>
                            <th>Date Added</th>
                            <th width="5%">Status</th>
                            <th width="1%">View</th>
                            <th width="1%">Approval</th>
                            <th width="1%">Edit</th>
                            <th width="1%">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($articles as $article)
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td>{{ $article->title }}</td>
                                <td>{{ $article->updated_at }}</td>
                                <td>@if($article->approved==true){{ 'Approved' }} @else{{ 'Unapproved' }} @endif</td>
                                <td><a  href="#" class="btn btn-outline-info btn-sm">View</a></td>

                                <td>
                                    @if($article->approved ==true)
                                        <form method="post" action=" {{ url('admin/article/disapprove',['id'=>$article->article_id]) }}">
                                            {{ method_field('PUT') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-outline-info btn-sm" title="Disapprove article">Disapprove</button>
                                        </form>
                                    @else
                                        <form method="post" action=" {{ url('admin/article/approve',['id'=>$article->article_id]) }}">
                                            {{ method_field('PUT') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-outline-info btn-sm">Approve</button>
                                        </form>
                                    @endif
                                </td>
                                <td><a href="{{ url('admin/article/'.$article->article_id.'/edit') }}" class="btn btn-outline-info btn-sm">Edit</a></td>
                                <td>
                                    <form method="post" action=" {{ url('admin/article',['id'=>$article->article_id]) }}">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">
            Newest Users
        </div>
        <div class="card-body">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Joined On</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $loop->index+1 }}</td>
                        <td>{{ $user->username }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

system/resources/views/admin/master2.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @section('styles')
        <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/font-awesome.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/admin.css') }}">
    @show


    <title>Culturepedia | Admin  |  @yield('title')</title>
</head>
<body>
<header>
    <nav class="container-fluid">
        <div class="navbar">
            <div class="logo">
                <h1>Culture<span class="colored">pedia</span></h1>
            </div>
        </div>
    </nav>
</header>
<aside>
    <div class="sidebar">
        <div class="links">
            <ul class="list-unstyled">
                <li ><a class="active" href="{{ url('/admin/dashboard') }}"><span class="fa fa-dashboard"></span> Dashboard</a> </li>
                <li><a href="{{ url('/admin/article/create') }}"> <span class="fa fa-pencil"></span> New Article</a> </li>
                <li><a href="{{ url('/admin/articles') }}"><span class="fa fa-compass"></span> My Articles</a></li>
                <li><a href="{{ url('/admin/articles/all') }}"><span class="fa fa-indent"></span> All Articles</a></li>
                <li><a href="{{ url('/admin/articles/unapproved') }}"><span class="fa fa-toggle-off"></span> Unapproved Articles</a> </li>
                <li><a href="{{ url('/admin/articles/approved') }}"><span class="fa fa-toggle-on"></span> Approved Articles</a></li>
                <li><a href="{{ url('/admin/users/all') }}"><span class="fa fa-users"></span> Users</a> </li>
            </ul>
        </div>
    </div>
</aside>
<main class="main">

    <section class="content">
        <div class="page-header">
            <h5>@yield('page-title')</h5>
        </div>
        @yield('content')
    </section>
</main>

@section('scripts')
    <script type="text/javascript" src="{{  asset('assets/js/jquery-3.3.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
@show
{{--<script type="text/javascript" src=" {{ asset('assets/js/custom.js') }}"></script>--}}
</body>
</html>

system/resources/views/admin/users.blade.php
@extends('admin.master')
@section('styles')
    @parent
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/datatables/datatables.css') }}">
@endsection
@section('title','All Articles')
@section('page-title','All Articles')


@section('header-title')
    <h1><span class="fa  fa-users "></span> Users<small> Manage Users</small></h1>
@endsection

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page">Users</li>
@endsection



@section('content')
        <div class="card">
            <div class="card-header">
              Users
            </div>
            <div class="card-body">
                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Joined On</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $loop->index+1 }}</td>
                            <td>{{ $user->username }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->created_at }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
@endsection
@section('scripts')
    @parent
    <script type="text/javascript" src="{{  asset('assets/datatables/datatables.js') }}"></script>
    <script>
        $(document).ready( function () {
            $('.table').DataTable({
                autoFill: true
            });
        } );
    </script>
@endsection